### ISSUE TITLE
Moment node accessible to jade templating engine

### ISSUE THREAD

**Issue by elropero** [mediapolis/digitopia-admin#1]
This is a great project, thanks for posting it and the attendant blog post. When incorporating it into my project, I encountered a crash because `moment` was not accessible to the jade templating engine. I had to apply the patch below:

https://github.com/buildproto/digitopia-admin/commit/7181002b53f8587100263d0354d55a4cb1c5d727

**Comment by mediapolis** [comment]
Thanks!
